spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/netrodb
spring.datasource.username=netro_user
spring.datasource.password=netropass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=yTX6D1l/v5BZG5GeKjj4ZDuVjR3ZkP4U+0S8QVs1fTI=
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=TRACE
logging.level.org.example.backend=TRACE
