spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/netrodb
spring.datasource.username=netro_user
spring.datasource.password=netropass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=Zm9vYmFyYmF6cXV4MTIzNDU2Nzg5MGFiY2RlZg==
